import express from "express";
import cors from "cors";
import cowRoutes from "./routes/cowroutes.ts";
import feedingRoutes from "./routes/feedingroutes.ts";
import { errorHandler } from "./middleware/errorhandler.ts";
import salesRoutes from "./routes/salesroutes.ts";
import dashboardRoutes from "./routes/dashboardroutes.ts";
import userRoutes from "./routes/userroutes.ts";
import milkRoutes from "./routes/milkroutes.ts";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/cows", cowRoutes);
app.use("/api/feeding", feedingRoutes);
app.use("/api/milk", milkRoutes);
app.get("/", (req, res) => res.send("API is running..."));
app.use("/api/sales", salesRoutes);
app.use("/api/dashboard", dashboardRoutes);
app.use("/api/users", userRoutes);
app.use("/api/dashboard", dashboardRoutes);
app.use(errorHandler);

export default app;